// Generated by tools/build-audio.mjs from content/audio/. Do not edit by hand.
// Dad's recordings that ship with the app, keyed by "<unit id>/<clip file>" (FR-05).

export const bundledClips: Record<string, number> = {
};
