#!/usr/bin/env node
// Builds app/src/content/audioClips.ts: a static require() for every clip in content/audio/<unit>/,
// because Metro can only bundle assets it can see in the code. Add Dad's clips to the folder, then run this.
// Usage: node tools/build-audio.mjs          (writes the file)
//        node tools/build-audio.mjs --check  (fails if out of date; used in CI)
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const audioDir = join(root, 'content', 'audio');
const outPath = join(root, 'app', 'src', 'content', 'audioClips.ts');
const EXTENSIONS = /\.(m4a|mp3|wav|aac)$/i;

const clips = [];
if (existsSync(audioDir)) {
  for (const unit of readdirSync(audioDir).sort()) {
    const dir = join(audioDir, unit);
    if (!statSync(dir).isDirectory()) continue;
    for (const file of readdirSync(dir).sort()) if (EXTENSIONS.test(file)) clips.push(`${unit}/${file}`);
  }
}

const lines = clips.map((c) => `  '${c}': require('../../../content/audio/${c}'),`);
const ts = `// Generated by tools/build-audio.mjs from content/audio/. Do not edit by hand.
// Dad's recordings that ship with the app, keyed by "<unit id>/<clip file>" (FR-05).

export const bundledClips: Record<string, number> = {
${lines.join('\n')}${lines.length ? '\n' : ''}};
`;

if (process.argv.includes('--check')) {
  let current = '';
  try { current = readFileSync(outPath, 'utf8'); } catch {}
  if (current !== ts) {
    console.error('app/src/content/audioClips.ts is out of date. Run: node tools/build-audio.mjs');
    process.exit(1);
  }
  console.log(`audioClips.ts is up to date (${clips.length} clips)`);
} else {
  writeFileSync(outPath, ts);
  console.log(`Wrote app/src/content/audioClips.ts (${clips.length} clips)`);
}
