#!/usr/bin/env node
// Draws the journey map (FR-21) from real coastlines: Ireland, Britain, France, Spain and Portugal from Natural Earth
// (public domain, via the world-atlas package). It writes app/assets/journey-map.svg and app/assets/journey-map.png,
// and sets each stop's x and y in content/journey.json from its lat/lon, so the stops sit on the right spot.
// The north is squeezed and Portugal stretched, so the five Portuguese stops have room.
//
// Usage: npm i --no-save --prefix tools world-atlas topojson-client playwright-core && node tools/build-map.mjs
// The PNG is rendered with Chromium: set CHROME to its path if it isn't the one in /opt/pw-browsers.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(join(root, 'tools', 'package.json'));
const { feature } = require('topojson-client');
const world = require('world-atlas/countries-50m.json');

// The map is 700 × 672, like the view that shows it.
const W = 700;
const H = 672;
const LON = [-12.2, 4.6];
// Latitude → fraction of the height, linear between these points.
const LAT = [
  [56.0, -0.01],
  [51.0, 0.28],
  [44.0, 0.47],
  [42.0, 0.5],
  [37.6, 1.08],
];

const fx = (lon) => (lon - LON[0]) / (LON[1] - LON[0]);
function fy(lat) {
  for (let i = 0; i < LAT.length - 1; i++) {
    const [a, ya] = LAT[i];
    const [b, yb] = LAT[i + 1];
    if (lat <= a && lat >= b) return ya + ((a - lat) / (a - b)) * (yb - ya);
  }
  return lat > LAT[0][0] ? LAT[0][1] : LAT.at(-1)[1] + (LAT.at(-1)[0] - lat) * 0.12;
}

const FILL = { Ireland: '#9FD18B', Portugal: '#F7C873', Spain: '#F4DDB0' };
const OTHER = '#E3E8DA';
const countries = feature(world, world.objects.countries).features;
const near = ['Ireland', 'United Kingdom', 'France', 'Spain', 'Portugal', 'Belgium', 'Andorra', 'Switzerland', 'Italy', 'Germany', 'Luxembourg', 'Netherlands', 'Morocco', 'Isle of Man'];

function path(geometry) {
  const polys = geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates;
  return polys
    .flatMap((poly) => poly)
    .filter((ring) => ring.some(([lon, lat]) => lon > LON[0] - 3 && lon < LON[1] + 3 && lat > 35 && lat < 58))
    .map((ring) => 'M' + ring.map(([lon, lat]) => `${(fx(lon) * W).toFixed(1)},${(fy(lat) * H).toFixed(1)}`).join('L') + 'Z')
    .join('');
}

const shapes = countries
  .filter((c) => near.includes(c.properties.name))
  .map((c) => `<path d="${path(c.geometry)}" fill="${FILL[c.properties.name] ?? OTHER}"/>`)
  .join('\n  ');

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
  <!-- Generated by tools/build-map.mjs from Natural Earth (public domain). Do not edit by hand. -->
  <rect width="${W}" height="${H}" fill="#BFDDF0"/>
  <g stroke="#1F2A44" stroke-width="2.5" stroke-linejoin="round">
  ${shapes}
  </g>
</svg>
`;
writeFileSync(join(root, 'app', 'assets', 'journey-map.svg'), svg);

const chrome = process.env.CHROME ?? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
if (existsSync(chrome)) {
  const { chromium } = require('playwright-core');
  const browser = await chromium.launch({ executablePath: chrome });
  const page = await browser.newPage({ viewport: { width: W, height: H }, deviceScaleFactor: 2 });
  await page.setContent(`<body style="margin:0">${svg}</body>`);
  await page.screenshot({ path: join(root, 'app', 'assets', 'journey-map.png') });
  await browser.close();
} else {
  console.warn(`No Chromium at ${chrome}: only the SVG was written.`);
}

const journeyPath = join(root, 'content', 'journey.json');
const journey = JSON.parse(readFileSync(journeyPath, 'utf8'));
for (const s of journey.stops) {
  s.x = Number(fx(s.lon).toFixed(3));
  s.y = Number(fy(s.lat).toFixed(3));
}
writeFileSync(journeyPath, JSON.stringify(journey, null, 2) + '\n');
console.log(journey.stops.map((s) => `${s.id} ${s.x},${s.y}`).join('\n'));
